<?php

declare(strict_types=1);

use InertiaAgentKit\Scaffolding\ResourceScaffolder;
use InertiaAgentKit\Scaffolding\ResourceScaffoldOptions;
use Tests\TestCase;
use Tests\Utils\ScaffoldingTestHelper;

uses(TestCase::class);

beforeEach(function (): void {
    $this->basePath = sys_get_temp_dir().'/iak-scaffold-unit-'.bin2hex(random_bytes(6));
    mkdir($this->basePath, 0755, true);
    $this->app->setBasePath($this->basePath);
    $this->scaffolder = new ResourceScaffolder($this->app);
});

afterEach(function (): void {
    $directory = $this->basePath ?? null;

    if (! is_string($directory) || ! is_dir($directory)) {
        return;
    }

    $items = new RecursiveIteratorIterator(
        new RecursiveDirectoryIterator($directory, FilesystemIterator::SKIP_DOTS),
        RecursiveIteratorIterator::CHILD_FIRST,
    );

    foreach ($items as $item) {
        $item->isDir() ? rmdir($item->getPathname()) : unlink($item->getPathname());
    }

    rmdir($directory);
});

test('creates a completed scaffold plan and writes generated files', function (): void {
    ScaffoldingTestHelper::writeGeneratedTypes($this->basePath, 'Vehicle');

    $plan = $this->scaffolder->scaffold(new ResourceScaffoldOptions(
        resource: 'vehicles',
        adapter: 'react',
        dryRun: false,
        force: false,
        singular: null,
        only: null,
        except: null,
        allowMissingGeneratedTypes: false,
        controller: null,
        routeName: null,
        command: 'php artisan iak:make-resource vehicles',
    ));

    expect($plan['status'])->toBe('completed')
        ->and($plan['mode'])->toBe('write')
        ->and($plan['errors'])->toBe([])
        ->and($plan['writtenFiles'])->toHaveCount(12)
        ->and($plan['skippedFiles'])->toBe([])
        ->and($plan['conflicts'])->toBe([])
        ->and($plan['resource'])->toMatchArray([
            'name' => 'vehicles',
            'singular' => 'vehicle',
            'folder' => 'vehicles',
        ]);

    foreach ([
        'resources/js/pages/vehicles/index.tsx',
        'resources/js/pages/vehicles/show.tsx',
        'resources/js/pages/vehicles/create.tsx',
        'resources/js/pages/vehicles/edit.tsx',
        'resources/js/features/vehicles/vehicle.types.ts',
        'resources/js/features/vehicles/vehicle.fixtures.ts',
        'resources/js/features/vehicles/vehicle-table.tsx',
        'resources/js/features/vehicles/vehicle-table.stories.tsx',
        'resources/js/features/vehicles/vehicle-filters.tsx',
        'resources/js/features/vehicles/vehicle-form.tsx',
        'resources/js/features/vehicles/vehicle-form.stories.tsx',
        'resources/js/features/vehicles/vehicle-empty-state.tsx',
    ] as $file) {
        expect(file_exists($this->basePath.'/'.$file))->toBeTrue();
        expect(file_get_contents($this->basePath.'/'.$file))->toContain('Generated by Inertia Agent Kit. Do not edit manually.');
    }
});

test('returns planned mode when dry-run is enabled', function (): void {
    ScaffoldingTestHelper::writeGeneratedTypes($this->basePath, 'Vehicle');

    $plan = $this->scaffolder->scaffold(new ResourceScaffoldOptions(
        resource: 'vehicles',
        adapter: 'react',
        dryRun: true,
        force: false,
        singular: null,
        only: null,
        except: null,
        allowMissingGeneratedTypes: false,
        controller: null,
        routeName: null,
        command: 'php artisan iak:make-resource vehicles --dry-run',
    ));

    expect($plan['status'])->toBe('planned')
        ->and($plan['mode'])->toBe('dry-run')
        ->and($plan['writtenFiles'])->toBe([])
        ->and($plan['skippedFiles'])->toBe([]);

    expect(file_exists($this->basePath.'/resources/js/pages/vehicles/index.tsx'))->toBeFalse();
});

test('skips writes when generated files already exist and force is false', function (): void {
    ScaffoldingTestHelper::writeGeneratedTypes($this->basePath, 'Vehicle');

    $this->scaffolder->scaffold(new ResourceScaffoldOptions(
        resource: 'vehicles',
        adapter: 'react',
        dryRun: false,
        force: false,
        singular: null,
        only: null,
        except: null,
        allowMissingGeneratedTypes: false,
        controller: null,
        routeName: null,
        command: 'php artisan iak:make-resource vehicles',
    ));

    $plan = $this->scaffolder->scaffold(new ResourceScaffoldOptions(
        resource: 'vehicles',
        adapter: 'react',
        dryRun: false,
        force: false,
        singular: null,
        only: null,
        except: null,
        allowMissingGeneratedTypes: false,
        controller: null,
        routeName: null,
        command: 'php artisan iak:make-resource vehicles',
    ));

    expect($plan['status'])->toBe('completed')
        ->and($plan['mode'])->toBe('write')
        ->and(array_column($plan['files'], 'action'))->toContain('skip')
        ->and($plan['skippedFiles'])->not->toBeEmpty()
        ->and($plan['writtenFiles'])->toBe([]);
});

test('updates generated files when force overwrite is enabled', function (): void {
    ScaffoldingTestHelper::writeGeneratedTypes($this->basePath, 'Vehicle');

    $this->scaffolder->scaffold(new ResourceScaffoldOptions(
        resource: 'vehicles',
        adapter: 'react',
        dryRun: false,
        force: false,
        singular: null,
        only: null,
        except: null,
        allowMissingGeneratedTypes: false,
        controller: null,
        routeName: null,
        command: 'php artisan iak:make-resource vehicles',
    ));

    $plan = $this->scaffolder->scaffold(new ResourceScaffoldOptions(
        resource: 'vehicles',
        adapter: 'react',
        dryRun: false,
        force: true,
        singular: null,
        only: null,
        except: null,
        allowMissingGeneratedTypes: false,
        controller: null,
        routeName: null,
        command: 'php artisan iak:make-resource vehicles --force',
    ));

    expect($plan['status'])->toBe('completed')
        ->and($plan['mode'])->toBe('write')
        ->and(array_column($plan['files'], 'action'))->toContain('overwrite')
        ->and($plan['writtenFiles'])->toHaveCount(12)
        ->and($plan['errors'])->toBe([]);
});

test('returns conflict errors when existing files are user-owned', function (): void {
    ScaffoldingTestHelper::writeGeneratedTypes($this->basePath, 'Vehicle');

    $this->scaffolder->scaffold(new ResourceScaffoldOptions(
        resource: 'vehicles',
        adapter: 'react',
        dryRun: false,
        force: false,
        singular: null,
        only: null,
        except: null,
        allowMissingGeneratedTypes: false,
        controller: null,
        routeName: null,
        command: 'php artisan iak:make-resource vehicles',
    ));

    file_put_contents($this->basePath.'/resources/js/features/vehicles/vehicle.types.ts', 'export type VehicleFormData = never;');

    $plan = $this->scaffolder->scaffold(new ResourceScaffoldOptions(
        resource: 'vehicles',
        adapter: 'react',
        dryRun: false,
        force: false,
        singular: null,
        only: null,
        except: null,
        allowMissingGeneratedTypes: false,
        controller: null,
        routeName: null,
        command: 'php artisan iak:make-resource vehicles',
    ));

    $conflicts = array_column($plan['errors'], 'code');

    expect($plan['status'])->toBe('failed')
        ->and($conflicts)->toContain('file-conflict')
        ->and($plan['writtenFiles'])->toBe([]);
});

test('returns unsupported-adapter when adapter is not react', function (): void {
    $plan = $this->scaffolder->scaffold(new ResourceScaffoldOptions(
        resource: 'vehicles',
        adapter: 'vue',
        dryRun: false,
        force: false,
        singular: null,
        only: null,
        except: null,
        allowMissingGeneratedTypes: false,
        controller: null,
        routeName: null,
        command: 'php artisan iak:make-resource vehicles --adapter=vue',
    ));

    expect($plan['status'])->toBe('failed')
        ->and($plan['errors'])->toHaveCount(1)
        ->and($plan['errors'][0]['code'])->toBe('unsupported-adapter');
});

test('fails when required singular is ambiguous and not provided', function (): void {
    $plan = $this->scaffolder->scaffold(new ResourceScaffoldOptions(
        resource: 'statuses',
        adapter: 'react',
        dryRun: false,
        force: false,
        singular: null,
        only: null,
        except: null,
        allowMissingGeneratedTypes: false,
        controller: null,
        routeName: null,
        command: 'php artisan iak:make-resource statuses',
    ));

    $codes = array_column($plan['errors'], 'code');

    expect($plan['status'])->toBe('failed')
        ->and($codes)->toContain('ambiguous-singular')
        ->and($plan['resource']['name'])->toBe('statuses');
});

test('validates mutating-only action configuration as page-action errors', function (): void {
    $plan = $this->scaffolder->scaffold(new ResourceScaffoldOptions(
        resource: 'vehicles',
        adapter: 'react',
        dryRun: false,
        force: false,
        singular: null,
        only: 'store',
        except: null,
        allowMissingGeneratedTypes: false,
        controller: null,
        routeName: null,
        command: 'php artisan iak:make-resource vehicles --only=store',
    ));

    $codes = array_column($plan['errors'], 'code');

    expect($plan['status'])->toBe('failed')
        ->and($codes)->toContain('mutating-action-not-page');
});

test('fails when generated type definitions are missing and no fallback is allowed', function (): void {
    $plan = $this->scaffolder->scaffold(new ResourceScaffoldOptions(
        resource: 'vehicles',
        adapter: 'react',
        dryRun: false,
        force: false,
        singular: null,
        only: null,
        except: null,
        allowMissingGeneratedTypes: false,
        controller: null,
        routeName: null,
        command: 'php artisan iak:make-resource vehicles',
    ));

    expect($plan['status'])->toBe('failed')
        ->and($plan['errors'][0]['code'])->toBe('missing-generated-types')
        ->and($plan['errors'][0]['context']['path'])->toBe('resources/js/types/generated/index.d.ts');
});

test('reports missing expected generated symbols while preserving failure status', function (): void {
    mkdir($this->basePath.'/resources/js/types/generated', 0755, true);
    file_put_contents($this->basePath.'/resources/js/types/generated/index.d.ts', <<<'TS'
export namespace App {
  export namespace Data {
    export namespace Vehicle {
      export type VehicleIndexPageData = never
    }
  }
}
TS);

    $plan = $this->scaffolder->scaffold(new ResourceScaffoldOptions(
        resource: 'vehicles',
        adapter: 'react',
        dryRun: false,
        force: false,
        singular: null,
        only: null,
        except: null,
        allowMissingGeneratedTypes: false,
        controller: null,
        routeName: null,
        command: 'php artisan iak:make-resource vehicles',
    ));

    expect($plan['status'])->toBe('failed')
        ->and($plan['errors'][0]['code'])->toBe('missing-generated-type-symbols')
        ->and($plan['errors'][0]['context']['path'])->toBe('resources/js/types/generated/index.d.ts')
        ->and($plan['errors'][0]['context']['symbols'][0])->toBe('VehicleShowPageData');
});

test('allows missing generated types when explicitly requested', function (): void {
    $plan = $this->scaffolder->scaffold(new ResourceScaffoldOptions(
        resource: 'vehicles',
        adapter: 'react',
        dryRun: false,
        force: false,
        singular: null,
        only: null,
        except: null,
        allowMissingGeneratedTypes: true,
        controller: null,
        routeName: null,
        command: 'php artisan iak:make-resource vehicles --allow-missing-generated-types',
    ));

    expect($plan['status'])->toBe('completed')
        ->and($plan['errors'])->toBe([])
        ->and($plan['writtenFiles'])->toHaveCount(12);
});

test('normalizes route names while resolving resources', function (): void {
    ScaffoldingTestHelper::writeGeneratedTypes($this->basePath, 'Member');

    $plan = $this->scaffolder->scaffold(new ResourceScaffoldOptions(
        resource: 'Admin/Users',
        adapter: 'react',
        dryRun: false,
        force: false,
        singular: 'member',
        only: null,
        except: null,
        allowMissingGeneratedTypes: false,
        controller: null,
        routeName: '  user-members  ',
        command: 'php artisan iak:make-resource admin/users',
    ));

    expect($plan['status'])->toBe('completed')
        ->and($plan['resource']['name'])->toBe('admin.users')
        ->and($plan['resource']['routeName'])->toBe('user-members');
});

test('returns an invalid resource error when resource normalization is empty', function (): void {
    ScaffoldingTestHelper::writeGeneratedTypes($this->basePath, 'Vehicle');

    $plan = $this->scaffolder->scaffold(new ResourceScaffoldOptions(
        resource: '///',
        adapter: 'react',
        dryRun: false,
        force: false,
        singular: null,
        only: null,
        except: null,
        allowMissingGeneratedTypes: false,
        controller: null,
        routeName: null,
        command: 'php artisan iak:make-resource ""',
    ));

    expect($plan['status'])->toBe('failed')
        ->and($plan['errors'][0]['code'])->toBe('invalid-resource')
        ->and($plan['resource']['name'])->toBe('')
        ->and($plan['resource']['routeName'])->toBe('');
});

test('returns an invalid singular error when normalized singular is empty', function (): void {
    ScaffoldingTestHelper::writeGeneratedTypes($this->basePath, 'Vehicle');

    $plan = $this->scaffolder->scaffold(new ResourceScaffoldOptions(
        resource: 'vehicles',
        adapter: 'react',
        dryRun: false,
        force: false,
        singular: '   ',
        only: null,
        except: null,
        allowMissingGeneratedTypes: false,
        controller: null,
        routeName: null,
        command: 'php artisan iak:make-resource vehicles',
    ));

    expect($plan['status'])->toBe('failed')
        ->and($plan['errors'][0]['code'])->toBe('invalid-singular');
});

test('validates only and except page actions for mutating and non-page actions', function (): void {
    ScaffoldingTestHelper::writeGeneratedTypes($this->basePath, 'Vehicle');

    $plan = $this->scaffolder->scaffold(new ResourceScaffoldOptions(
        resource: 'vehicles',
        adapter: 'react',
        dryRun: false,
        force: false,
        singular: null,
        only: 'index,store,foo',
        except: null,
        allowMissingGeneratedTypes: false,
        controller: null,
        routeName: null,
        command: 'php artisan iak:make-resource vehicles --only=index,store,foo',
    ));

    expect($plan['status'])->toBe('failed')
        ->and(array_column($plan['errors'], 'code'))->toContain('mutating-action-not-page')
        ->toContain('invalid-page-action');

    $plan = $this->scaffolder->scaffold(new ResourceScaffoldOptions(
        resource: 'vehicles',
        adapter: 'react',
        dryRun: false,
        force: false,
        singular: null,
        only: null,
        except: 'update,foo',
        allowMissingGeneratedTypes: false,
        controller: null,
        routeName: null,
        command: 'php artisan iak:make-resource vehicles --except=update,foo',
    ));

    expect($plan['status'])->toBe('failed')
        ->and(array_column($plan['errors'], 'code'))->toContain('mutating-action-not-page')
        ->toContain('invalid-page-action');
});

test('throws when scaffold file directories cannot be created', function (): void {
    $writeFiles = new ReflectionMethod($this->scaffolder, 'writeFiles');

    mkdir($this->basePath.'/resources/js/pages', 0755, true);
    rmdir($this->basePath.'/resources/js/pages');
    file_put_contents($this->basePath.'/resources/js/pages', 'blocked');

    set_error_handler(static fn (): bool => true);

    try {
        expect(fn () => $writeFiles->invoke($this->scaffolder, [
            [
                'path' => 'resources/js/pages/vehicles/index.tsx',
                'action' => 'create',
                'contents' => 'content',
            ],
        ]))->toThrow(RuntimeException::class, 'Unable to create directory');
    } finally {
        restore_error_handler();
    }
});

test('throws when scaffold file writes fail', function (): void {
    $writeFiles = new ReflectionMethod($this->scaffolder, 'writeFiles');

    mkdir($this->basePath.'/resources', 0755, true);
    mkdir($this->basePath.'/resources/js', 0755, true);

    set_error_handler(static fn (): bool => true);

    try {
        expect(fn () => $writeFiles->invoke($this->scaffolder, [
            [
                'path' => 'resources/js',
                'action' => 'create',
                'contents' => 'content',
            ],
        ]))->toThrow(RuntimeException::class, 'Unable to write file [resources/js].');
    } finally {
        restore_error_handler();
    }
});

test('throws when attempting to read a generated file entry without a string path', function (): void {
    $fileString = new ReflectionMethod($this->scaffolder, 'fileString');

    expect(fn () => $fileString->invoke($this->scaffolder, ['path' => []], 'path'))
        ->toThrow(RuntimeException::class, 'Generated file [path] must be a string.');
});
