<?php

declare(strict_types=1);

namespace InertiaAgentKit\Scaffolding;

use Illuminate\Contracts\Foundation\Application;
use Illuminate\Support\Str;
use InertiaAgentKit\Support\ProjectPaths;
use RuntimeException;

final class ResourceScaffolder
{
    private const SCHEMA = 'iak.scaffold-plan.v1';

    private const GENERATED_MARKER = 'Generated by Inertia Agent Kit. Do not edit manually.';

    private const PAGE_ACTIONS = [
        'index',
        'show',
        'create',
        'edit',
    ];

    private const MUTATING_ACTIONS = [
        'store',
        'update',
        'destroy',
    ];

    /**
     * @var array<string, string>
     */
    private const FEATURE_STUBS = [
        'types.ts.stub' => ':singular.types.ts',
        'fixtures.ts.stub' => ':singular.fixtures.ts',
        'table.tsx.stub' => ':singular-table.tsx',
        'table.stories.tsx.stub' => ':singular-table.stories.tsx',
        'filters.tsx.stub' => ':singular-filters.tsx',
        'form.tsx.stub' => ':singular-form.tsx',
        'form.stories.tsx.stub' => ':singular-form.stories.tsx',
        'empty-state.tsx.stub' => ':singular-empty-state.tsx',
    ];

    private readonly ProjectPaths $paths;

    public function __construct(
        private readonly Application $app,
        private readonly ResourceStubRenderer $renderer = new ResourceStubRenderer()
    ) {
        $this->paths = new ProjectPaths($app);
    }

    /**
     * @return array<string, mixed>
     */
    public function scaffold(ResourceScaffoldOptions $options): array
    {
        $errors = [];
        $warnings = [];

        $adapter = $options->adapter !== '' ? $options->adapter : (string) config('inertia-agent-kit.adapter', 'react');

        if ($adapter !== 'react') {
            $errors[] = $this->error('unsupported-adapter', 'Only the react adapter is supported in this package port.', [
                'adapter' => $adapter,
            ]);
        }

        if (trim($options->resource) === '') {
            $errors[] = $this->error('missing-resource', 'The resource argument is required.');
        }

        $resource = $errors === []
            ? $this->resolveResource($options, $errors)
            : $this->emptyResource();

        $pageActions = $this->selectedPageActions($options, $errors);
        $context = $errors === [] ? $this->context($resource, $adapter) : [];
        $files = $errors === [] ? $this->plannedFiles($resource, $pageActions, $context) : [];
        $controllerMap = $errors === [] ? $this->controllerMap($resource, $pageActions) : [];
        $generatedTypeImports = $errors === [] ? $this->generatedTypeImports($resource) : [];
        $wayfinderImports = $errors === [] ? $this->wayfinderImports($resource) : [];
        $stories = $errors === [] ? $this->stories($resource) : [];

        if ($errors === [] && ! $options->allowMissingGeneratedTypes) {
            $errors = [
                ...$errors,
                ...$this->validateGeneratedTypes($resource),
            ];
        }

        $conflicts = [];
        $skippedFiles = [];

        if ($errors === []) {
            [$files, $conflicts, $skippedFiles] = $this->markFileActions($files, $options->force);
        }

        if ($conflicts !== []) {
            foreach ($conflicts as $conflict) {
                $errors[] = $this->error('file-conflict', 'Existing user-owned file would be overwritten.', [
                    'path' => $conflict['path'],
                ]);
            }
        }

        $writtenFiles = [];

        if ($errors === [] && ! $options->dryRun) {
            $writtenFiles = $this->writeFiles($files);
        }

        return [
            'schema' => self::SCHEMA,
            'command' => $options->command,
            'status' => $errors === [] ? ($options->dryRun ? 'planned' : 'completed') : 'failed',
            'mode' => $options->dryRun ? 'dry-run' : 'write',
            'adapter' => $adapter,
            'resource' => $resource,
            'controllerMap' => $controllerMap,
            'files' => $this->publicFiles($files),
            'generatedTypeImports' => $generatedTypeImports,
            'wayfinderImports' => $wayfinderImports,
            'stories' => $stories,
            'writtenFiles' => $writtenFiles,
            'skippedFiles' => $options->dryRun ? [] : $skippedFiles,
            'conflicts' => $conflicts,
            'warnings' => $warnings,
            'errors' => $errors,
        ];
    }

    /**
     * @param array<int, array<string, mixed>> $errors
     *
     * @return array<string, mixed>
     */
    private function resolveResource(ResourceScaffoldOptions $options, array &$errors): array
    {
        $name = $this->normalizeResourceName($options->resource);
        $routeName = $options->routeName !== null
            ? $this->normalizeResourceName($options->routeName)
            : $name;

        if ($name === '' || $routeName === '') {
            $errors[] = $this->error('invalid-resource', 'The resource name must include at least one kebab-case segment.');

            return $this->emptyResource();
        }

        $segments = explode('.', $name);
        $pluralSegment = (string) end($segments);

        if ($options->singular === null && $this->requiresExplicitSingular($pluralSegment)) {
            $errors[] = $this->error('ambiguous-singular', 'The resource singular name is ambiguous. Pass --singular to continue.', [
                'resource' => $name,
            ]);
        }

        $singular = $options->singular !== null
            ? $this->normalizeKebab($options->singular)
            : $this->normalizeKebab(Str::singular($pluralSegment));

        if ($singular === '') {
            $errors[] = $this->error('invalid-singular', 'The singular resource name must include at least one kebab-case segment.');
        }

        $singularStudly = Str::studly($singular);
        $pluralStudly = Str::studly($pluralSegment);
        $controller = $options->controller ?? "App\\Http\\Controllers\\{$singularStudly}Controller";

        return [
            'name' => $name,
            'singular' => $singular,
            'folder' => str_replace('.', '/', $name),
            'routeName' => $routeName,
            'controller' => $controller,
            'controllerBasename' => class_basename($controller),
            'singularStudly' => $singularStudly,
            'pluralStudly' => $pluralStudly,
            'generatedTypeNamespace' => 'App.Data.'.$pluralStudly,
        ];
    }

    /**
     * @param array<int, array<string, mixed>> $errors
     *
     * @return array<int, string>
     */
    private function selectedPageActions(ResourceScaffoldOptions $options, array &$errors): array
    {
        $actions = self::PAGE_ACTIONS;

        if ($options->only !== null) {
            $only = $this->csv($options->only);
            $invalid = array_values(array_diff($only, self::PAGE_ACTIONS));

            foreach (array_intersect($only, self::MUTATING_ACTIONS) as $action) {
                $errors[] = $this->error('mutating-action-not-page', "The {$action} action does not generate a page.", [
                    'action' => $action,
                ]);
            }

            $invalid = array_values(array_diff($invalid, self::MUTATING_ACTIONS));

            if ($invalid !== []) {
                $errors[] = $this->error('invalid-page-action', 'Only index, show, create, and edit page actions can be scaffolded.', [
                    'actions' => $invalid,
                ]);
            }

            $actions = array_values(array_intersect(self::PAGE_ACTIONS, $only));
        }

        if ($options->except !== null) {
            $except = $this->csv($options->except);
            $invalid = array_values(array_diff($except, self::PAGE_ACTIONS));

            foreach (array_intersect($except, self::MUTATING_ACTIONS) as $action) {
                $errors[] = $this->error('mutating-action-not-page', "The {$action} action does not generate a page.", [
                    'action' => $action,
                ]);
            }

            $invalid = array_values(array_diff($invalid, self::MUTATING_ACTIONS));

            if ($invalid !== []) {
                $errors[] = $this->error('invalid-page-action', 'Only index, show, create, and edit page actions can be scaffolded.', [
                    'actions' => $invalid,
                ]);
            }

            $actions = array_values(array_diff($actions, $except));
        }

        return $actions;
    }

    /**
     * @param array<string, mixed> $resource
     *
     * @return array<string, string>
     */
    private function context(array $resource, string $adapter): array
    {
        $singularStudly = (string) $resource['singularStudly'];
        $pluralStudly = (string) $resource['pluralStudly'];
        $singularKebab = (string) $resource['singular'];
        $folder = (string) $resource['folder'];

        return [
            'generatedMarker' => self::GENERATED_MARKER,
            'adapter' => $adapter,
            'resourceName' => (string) $resource['name'],
            'resourceFolder' => $folder,
            'routeName' => (string) $resource['routeName'],
            'controller' => (string) $resource['controller'],
            'controllerBasename' => (string) $resource['controllerBasename'],
            'singularKebab' => $singularKebab,
            'pluralKebab' => Str::kebab($pluralStudly),
            'singularCamel' => Str::camel($singularKebab),
            'pluralCamel' => Str::camel($pluralStudly),
            'singularStudly' => $singularStudly,
            'pluralStudly' => $pluralStudly,
            'generatedTypeAlias' => (string) config('inertia-agent-kit.generated.type_alias', '@/types/generated'),
            'generatedTypeNamespace' => (string) $resource['generatedTypeNamespace'],
            'actionsImportPath' => '@/actions/generated/'.str_replace('\\', '/', (string) $resource['controller']),
            'routesImportPath' => '@/routes/generated/'.$folder,
            'featureImportBase' => '@/features/'.$folder.'/'.$singularKebab,
            'localTypesImport' => './'.$singularKebab.'.types',
            'localFixturesImport' => './'.$singularKebab.'.fixtures',
            'localTableImport' => './'.$singularKebab.'-table',
            'localFiltersImport' => './'.$singularKebab.'-filters',
            'localFormImport' => './'.$singularKebab.'-form',
            'localEmptyStateImport' => './'.$singularKebab.'-empty-state',
            'indexPagePropsType' => "{$singularStudly}IndexPageProps",
            'showPagePropsType' => "{$singularStudly}ShowPageProps",
            'createPagePropsType' => "{$singularStudly}CreatePageProps",
            'editPagePropsType' => "{$singularStudly}EditPageProps",
            'listItemType' => "{$singularStudly}ListItem",
            'formValuesType' => "{$singularStudly}FormValues",
            'filtersType' => "{$singularStudly}Filters",
            'tableComponent' => "{$singularStudly}Table",
            'filtersComponent' => "{$singularStudly}Filters",
            'formComponent' => "{$singularStudly}Form",
            'emptyStateComponent' => "{$singularStudly}EmptyState",
        ];
    }

    /**
     * @param array<string, mixed> $resource
     * @param array<int, string> $pageActions
     * @param array<string, string> $context
     *
     * @return array<int, array<string, mixed>>
     */
    private function plannedFiles(array $resource, array $pageActions, array $context): array
    {
        $files = [];
        $pagesPath = (string) config('inertia-agent-kit.paths.pages', 'resources/js/pages');
        $featuresPath = (string) config('inertia-agent-kit.paths.features', 'resources/js/features');
        $folder = (string) $resource['folder'];

        foreach ($pageActions as $pageAction) {
            $pageContext = [
                ...$context,
                'pageAction' => $pageAction,
                'pageComponent' => (string) $resource['singularStudly'].Str::studly($pageAction).'Page',
                'pagePropsType' => (string) $context[$pageAction.'PagePropsType'],
            ];

            $files[] = [
                'path' => "{$pagesPath}/{$folder}/{$pageAction}.tsx",
                'role' => 'page',
                'pageAction' => $pageAction,
                'stub' => "pages/{$pageAction}.tsx.stub",
                'contents' => $this->renderer->render('react', "pages/{$pageAction}.tsx.stub", $pageContext),
            ];
        }

        foreach (self::FEATURE_STUBS as $stub => $target) {
            $target = str_replace(':singular', (string) $resource['singular'], $target);

            $files[] = [
                'path' => "{$featuresPath}/{$folder}/{$target}",
                'role' => $this->featureRole($stub),
                'stub' => "features/{$stub}",
                'contents' => $this->renderer->render('react', "features/{$stub}", $context),
            ];
        }

        return $files;
    }

    /**
     * @param array<string, mixed> $resource
     * @param array<int, string> $pageActions
     *
     * @return array<int, array<string, string>>
     */
    private function controllerMap(array $resource, array $pageActions): array
    {
        return array_map(
            fn (string $action): array => [
                'controllerAction' => $resource['controllerBasename'].'@'.$action,
                'route' => $resource['routeName'].'.'.$action,
                'page' => config('inertia-agent-kit.paths.pages', 'resources/js/pages').'/'.$resource['folder'].'/'.$action.'.tsx',
            ],
            $pageActions
        );
    }

    /**
     * @param array<string, mixed> $resource
     *
     * @return array<int, array<string, mixed>>
     */
    private function generatedTypeImports(array $resource): array
    {
        return [
            [
                'from' => (string) config('inertia-agent-kit.generated.type_alias', '@/types/generated'),
                'symbols' => ['App'],
                'usedBy' => config('inertia-agent-kit.paths.features', 'resources/js/features').'/'.$resource['folder'].'/'.$resource['singular'].'.types.ts',
            ],
        ];
    }

    /**
     * @param array<string, mixed> $resource
     *
     * @return array<int, array<string, mixed>>
     */
    private function wayfinderImports(array $resource): array
    {
        return [
            [
                'from' => '@/actions/generated/'.str_replace('\\', '/', (string) $resource['controller']),
                'symbols' => ['store', 'update', 'destroy'],
            ],
            [
                'from' => '@/routes/generated/'.$resource['folder'],
                'symbols' => self::PAGE_ACTIONS,
            ],
        ];
    }

    /**
     * @param array<string, mixed> $resource
     *
     * @return array<int, array<string, mixed>>
     */
    private function stories(array $resource): array
    {
        $featuresPath = (string) config('inertia-agent-kit.paths.features', 'resources/js/features');
        $basePath = "{$featuresPath}/{$resource['folder']}";
        $singular = (string) $resource['singular'];
        $singularStudly = (string) $resource['singularStudly'];

        return [
            [
                'component' => "{$singularStudly}Table",
                'path' => "{$basePath}/{$singular}-table.stories.tsx",
                'fixture' => "{$basePath}/{$singular}.fixtures.ts",
                'states' => ['Default', 'Empty', 'Loading', 'Error'],
            ],
            [
                'component' => "{$singularStudly}Form",
                'path' => "{$basePath}/{$singular}-form.stories.tsx",
                'fixture' => "{$basePath}/{$singular}.fixtures.ts",
                'states' => ['Default', 'WithValidationErrors', 'Disabled'],
            ],
        ];
    }

    /**
     * @param array<int, array<string, mixed>> $files
     *
     * @return array{0: array<int, array<string, mixed>>, 1: array<int, array<string, string>>, 2: array<int, string>}
     */
    private function markFileActions(array $files, bool $force): array
    {
        $conflicts = [];
        $skippedFiles = [];

        foreach ($files as $index => $file) {
            $absolute = $this->paths->absolute((string) $file['path']);

            if (! is_file($absolute)) {
                $files[$index]['action'] = 'create';
                continue;
            }

            $contents = file_get_contents($absolute) ?: '';

            if (! str_contains($contents, self::GENERATED_MARKER)) {
                $files[$index]['action'] = 'conflict';
                $conflicts[] = [
                    'path' => (string) $file['path'],
                    'reason' => 'existing user-owned file',
                ];
                continue;
            }

            if ($force) {
                $files[$index]['action'] = 'overwrite';
                continue;
            }

            $files[$index]['action'] = 'skip';
            $skippedFiles[] = (string) $file['path'];
        }

        return [$files, $conflicts, $skippedFiles];
    }

    /**
     * @param array<int, array<string, mixed>> $files
     *
     * @return array<int, string>
     */
    private function writeFiles(array $files): array
    {
        $writtenFiles = [];

        foreach ($files as $file) {
            if (! in_array($file['action'], ['create', 'overwrite'], true)) {
                continue;
            }

            $path = (string) $file['path'];
            $directory = dirname($this->paths->absolute($path));

            if (! is_dir($directory) && ! mkdir($directory, 0755, true) && ! is_dir($directory)) {
                throw new RuntimeException("Unable to create directory [{$directory}].");
            }

            if (file_put_contents($this->paths->absolute($path), (string) $file['contents']) === false) {
                throw new RuntimeException("Unable to write file [{$path}].");
            }

            $writtenFiles[] = $path;
        }

        return $writtenFiles;
    }

    /**
     * @param array<int, array<string, mixed>> $files
     *
     * @return array<int, array<string, mixed>>
     */
    private function publicFiles(array $files): array
    {
        return array_map(
            static fn (array $file): array => array_filter([
                'path' => $file['path'],
                'role' => $file['role'],
                'pageAction' => $file['pageAction'] ?? null,
                'action' => $file['action'] ?? 'create',
            ], static fn (mixed $value): bool => $value !== null),
            $files
        );
    }

    /**
     * @param array<string, mixed> $resource
     *
     * @return array<int, array<string, mixed>>
     */
    private function validateGeneratedTypes(array $resource): array
    {
        $path = (string) config('inertia-agent-kit.generated.types', 'resources/js/types/generated/index.d.ts');
        $absolute = $this->paths->absolute($path);

        if (! is_file($absolute)) {
            return [
                $this->error('missing-generated-types', 'Generated backend contract types were not found. Pass --allow-missing-generated-types to scaffold expected imports anyway.', [
                    'path' => $path,
                ]),
            ];
        }

        $contents = file_get_contents($absolute) ?: '';
        $missing = array_values(array_filter($this->expectedGeneratedSymbols($resource), static fn (string $symbol): bool => ! str_contains($contents, $symbol)));

        if ($missing === []) {
            return [];
        }

        return [
            $this->error('missing-generated-type-symbols', 'Generated backend contract types are missing expected resource symbols. Pass --allow-missing-generated-types to scaffold expected imports anyway.', [
                'path' => $path,
                'symbols' => $missing,
            ]),
        ];
    }

    /**
     * @param array<string, mixed> $resource
     *
     * @return array<int, string>
     */
    private function expectedGeneratedSymbols(array $resource): array
    {
        $singularStudly = (string) $resource['singularStudly'];

        return [
            "{$singularStudly}IndexPageData",
            "{$singularStudly}ShowPageData",
            "{$singularStudly}CreatePageData",
            "{$singularStudly}EditPageData",
            "{$singularStudly}ListItemData",
            "{$singularStudly}FormData",
            "{$singularStudly}FiltersData",
        ];
    }

    private function normalizeResourceName(string $resource): string
    {
        $resource = str_replace('/', '.', trim($resource, " \t\n\r\0\x0B./"));
        $segments = array_values(array_filter(explode('.', $resource), static fn (string $segment): bool => trim($segment) !== ''));

        return implode('.', array_map(fn (string $segment): string => $this->normalizeKebab($segment), $segments));
    }

    private function normalizeKebab(string $value): string
    {
        return trim(Str::kebab($value), '-');
    }

    private function requiresExplicitSingular(string $pluralSegment): bool
    {
        return in_array($pluralSegment, ['statuses'], true);
    }

    /**
     * @return array<int, string>
     */
    private function csv(string $value): array
    {
        return array_values(array_filter(
            array_map(static fn (string $item): string => trim($item), explode(',', strtolower($value))),
            static fn (string $item): bool => $item !== ''
        ));
    }

    private function featureRole(string $stub): string
    {
        return match ($stub) {
            'types.ts.stub' => 'feature-types',
            'fixtures.ts.stub' => 'feature-fixtures',
            'table.tsx.stub' => 'feature-table',
            'table.stories.tsx.stub' => 'feature-story',
            'filters.tsx.stub' => 'feature-filters',
            'form.tsx.stub' => 'feature-form',
            'form.stories.tsx.stub' => 'feature-story',
            'empty-state.tsx.stub' => 'feature-empty-state',
            default => 'feature',
        };
    }

    /**
     * @param array<string, mixed> $context
     *
     * @return array<string, mixed>
     */
    private function error(string $code, string $message, array $context = []): array
    {
        return [
            'code' => $code,
            'message' => $message,
            'context' => $context === [] ? (object) [] : $context,
        ];
    }

    /**
     * @return array<string, mixed>
     */
    private function emptyResource(): array
    {
        return [
            'name' => '',
            'singular' => '',
            'folder' => '',
            'routeName' => '',
            'controller' => '',
        ];
    }
}
