import {
  existsSync,
  mkdirSync,
  readdirSync,
  readFileSync,
  rmSync,
  statSync,
  writeFileSync,
} from "node:fs";
import { basename, dirname, extname, join, relative } from "node:path";

export const CONFIG_FILE = "iak.config.json";
const GENERATED_HEADER = "// Generated by Inertia Agent Kit. Do not edit manually.";
const SCAN_EXT = new Set([".tsx", ".ts", ".jsx", ".js", ".vue", ".svelte", ".css"]);
const SKIP_DIRS = new Set(["node_modules", "vendor", "dist", "build", ".git", ".iak"]);
const TOKEN_FILE = /(tokens|themes)\.css$/;
const FORBIDDEN_TOP_LEVEL = ["queries", "forms", "hooks", "composables"];
const PROPS = [
  "p", "px", "py", "pt", "pb", "pl", "pr", "m", "mx", "my", "mt", "mb", "ml", "mr",
  "w", "h", "size", "min-w", "min-h", "max-w", "max-h", "gap", "text", "bg",
  "border", "rounded", "leading", "tracking", "shadow", "grid-cols",
];
const CLASS_PREFIX = "(?:^|[\\s\"'`:{])";
const ARBITRARY = new RegExp(`${CLASS_PREFIX}(?:${PROPS.join("|")})-\\[[^\\]]+\\]`, "g");
const RAW_HEX = /#[0-9a-fA-F]{3,8}\b/g;
const PALETTE = "slate|gray|zinc|neutral|stone|red|orange|amber|yellow|lime|green|emerald|teal|cyan|sky|blue|indigo|violet|purple|fuchsia|pink|rose";
const COLOR_UTIL = "bg|text|border|ring|fill|stroke|from|via|to|outline|decoration|divide|placeholder|caret|accent";
const PRIMITIVE_COLOR = new RegExp(
  `${CLASS_PREFIX}(?:${COLOR_UTIL})-(?:(?:${PALETTE})-\\d{2,3}|white|black)\\b`,
  "g",
);

function parse(args) {
  const out = { _: [], apply: false, json: process.env.IAK_AGENT === "1" };
  for (let i = 0; i < args.length; i++) {
    const arg = args[i];
    if (arg === "--apply" || arg === "-y") out.apply = true;
    else if (arg === "--json") out.json = true;
    else if (arg === "--target") out.target = args[++i];
    else if (arg === "--adapter") out.adapter = args[++i];
    else if (arg === "--run-id") out.runId = args[++i];
    else if (arg === "--id") out.id = args[++i];
    else if (arg === "--message") out.message = args[++i];
    else if (arg === "--route") out.route = args[++i];
    else if (arg === "--surface") out.surface = args[++i];
    else if (arg === "--source") out.source = args[++i];
    else if (arg === "--producer") out.producer = args[++i];
    else if (arg === "--status") out.status = args[++i];
    else if (arg === "--summary") out.summary = args[++i];
    else if (arg === "--evidence") out.evidence = args[++i];
    else if (arg === "--force") out.force = true;
    else out._.push(arg);
  }
  out.target ||= process.cwd();
  return out;
}

const posix = (path) => path.split(/[\\/]+/).filter(Boolean).join("/");
const now = () => new Date().toISOString();
const runId = (opt) => opt.runId || `run_${Date.now().toString(36)}`;
const feedbackId = (opt) => opt.id || `fbk_${Date.now().toString(36)}`;
const ensureDir = (path) => mkdirSync(path, { recursive: true });
const readJson = (path) => {
  try { return JSON.parse(readFileSync(path, "utf8")); } catch { return null; }
};

function writeJson(path, value) {
  ensureDir(dirname(path));
  writeFileSync(path, `${JSON.stringify(value, null, 2)}\n`);
}

function relPath(target, path) {
  return posix(relative(target, path));
}

function kebab(input) {
  return String(input)
    .replace(/Controller$/, "")
    .replace(/([a-z0-9])([A-Z])/g, "$1-$2")
    .replace(/[_\s]+/g, "-")
    .replace(/-+/g, "-")
    .toLowerCase();
}

function camel(input) {
  const parts = kebab(input).split("-");
  return parts[0] + parts.slice(1).map((x) => x.charAt(0).toUpperCase() + x.slice(1)).join("");
}

function pascal(input) {
  return kebab(input).split("-").map((x) => x.charAt(0).toUpperCase() + x.slice(1)).join("");
}

function singular(resource) {
  if (resource.endsWith("ies")) return `${resource.slice(0, -3)}y`;
  if (resource.endsWith("ses")) return resource.slice(0, -2);
  if (resource.endsWith("s")) return resource.slice(0, -1);
  return resource;
}

function detectAdapter(target, explicit) {
  if (explicit) return explicit;
  const pkg = readJson(join(target, "package.json")) || {};
  const deps = { ...(pkg.dependencies || {}), ...(pkg.devDependencies || {}) };
  if (deps["@inertiajs/vue3"] || deps.vue) return "vue";
  if (deps["@inertiajs/svelte"] || deps.svelte) return "svelte";
  return "react";
}

function baseConfig(target, opt = {}) {
  const adapter = detectAdapter(target, opt.adapter);
  const root = "resources/js";
  return {
    schema: "iak.config.v1",
    project: {
      framework: "laravel",
      inertia: true,
      adapter: `laravel-inertia-${adapter}`,
    },
    paths: {
      root,
      pages: `${root}/pages`,
      features: `${root}/features`,
      componentsUi: `${root}/components/ui`,
      componentsApp: `${root}/components/app`,
      layouts: `${root}/layouts`,
      typesGenerated: `${root}/types/generated`,
      css: "resources/css/iak",
      manifest: ".iak/manifest/iak.manifest.v1.json",
      feedback: ".iak/feedback",
      runs: ".iak/runs",
    },
    generated: {
      types: `${root}/types/generated/index.d.ts`,
      routes: `${root}/routes/generated`,
      actions: `${root}/actions/generated`,
    },
    conventions: {
      pages: "route-adapters-only",
      features: "resource-local-ui",
      formatting: "backend-owned",
      translations: "backend-owned",
      styling: "semantic-design-system-tokens-only",
    },
    commands: {
      audit: "iak audit --json",
      verify: "iak verify --json",
    },
  };
}

function loadConfig(target) {
  return readJson(join(target, CONFIG_FILE)) || baseConfig(target);
}

function filePlan(target, files, apply) {
  const plan = { create: [], skip: [], review: [] };
  for (const file of files) {
    const abs = join(target, file.path);
    if (!existsSync(abs)) {
      plan.create.push({ path: file.path });
      if (apply) {
        ensureDir(dirname(abs));
        writeFileSync(abs, file.content);
      }
      continue;
    }
    const current = readFileSync(abs, "utf8");
    if (current === file.content) plan.skip.push({ path: file.path });
    else plan.review.push({ path: file.path });
  }
  return plan;
}

function initFiles(config) {
  return [
    {
      path: ".iak/rules/frontend.md",
      content: `# Inertia Agent Kit Frontend Rules

- Pages in \`${config.paths.pages}\` are Inertia route adapters only.
- Resource behavior starts in \`${config.paths.features}/<resource>\`.
- Do not create top-level queries, actions, forms, hooks, or composables folders.
- Import backend-derived contracts from \`@/types/generated\`.
- Laravel owns translations, labels, dates, money, validation copy, and pluralization.
- Use semantic design-system utilities such as \`bg-ds-surface\` and \`text-ds-fg\`.
`,
    },
    {
      path: `${config.paths.css}/tokens.css`,
      content: `@theme {
  --color-iak-white: #ffffff;
  --color-iak-black: #111111;
  --spacing-iak-4: 1rem;
}
`,
    },
    {
      path: `${config.paths.css}/themes.css`,
      content: `:root {
  --ds-surface: var(--color-iak-white);
  --ds-fg: var(--color-iak-black);
  --ds-muted: #f4f4f5;
  --ds-border: #d4d4d8;
  --ds-action: #2563eb;
}
`,
    },
    {
      path: `${config.paths.css}/bridge.css`,
      content: `@theme {
  --color-ds-surface: var(--ds-surface);
  --color-ds-fg: var(--ds-fg);
  --color-ds-muted: var(--ds-muted);
  --color-ds-border: var(--ds-border);
  --color-ds-action: var(--ds-action);
}
`,
    },
    {
      path: `${config.paths.layouts}/app-layout.tsx`,
      content: `import type { ReactNode } from 'react'

export function AppLayout({ children }: { children: ReactNode }) {
  return <main className="min-h-screen bg-ds-surface text-ds-fg">{children}</main>
}
`,
    },
    {
      path: `${config.paths.componentsUi}/button.tsx`,
      content: `import type { ButtonHTMLAttributes } from 'react'

type ButtonProps = ButtonHTMLAttributes<HTMLButtonElement>

export function Button({ className = '', ...props }: ButtonProps) {
  return (
    <button
      className={\`rounded border border-ds-border bg-ds-action px-4 py-2 text-ds-surface \${className}\`}
      {...props}
    />
  )
}
`,
    },
    {
      path: `${config.paths.componentsUi}/button.stories.tsx`,
      content: `import type { Meta, StoryObj } from '@storybook/react'
import { Button } from './button'

const meta = {
  title: 'UI/Button',
  component: Button,
  args: { children: 'Save' },
} satisfies Meta<typeof Button>

export default meta
export const Default: StoryObj<typeof meta> = {}
`,
    },
    {
      path: `${config.paths.typesGenerated}/index.d.ts`,
      content: `${GENERATED_HEADER}

export namespace App {
  export namespace Data {
    export namespace Shared {
      export type ActionData = { label: string; href: string | null }
      export type PageMetaData = { title: string; description: string | null }
      export type SelectOptionData = { value: string; label: string }
    }
  }
}
`,
    },
  ];
}

function writeManifest(target, config) {
  const resources = [];
  const features = join(target, config.paths.features);
  if (existsSync(features)) {
    for (const name of readdirSync(features).sort()) {
      const abs = join(features, name);
      if (statSync(abs).isDirectory()) resources.push({ name, path: `${config.paths.features}/${name}` });
    }
  }
  const manifest = {
    schema: "iak.manifest.v1",
    generatedAt: now(),
    project: config.project,
    paths: config.paths,
    resources,
    conventions: config.conventions,
    commands: config.commands,
  };
  writeJson(join(target, config.paths.manifest), manifest);
  return manifest;
}

function appendGitignore(target) {
  const path = join(target, ".gitignore");
  const current = existsSync(path) ? readFileSync(path, "utf8") : "";
  const lines = [".iak/feedback/", ".iak/runs/"];
  const next = [...lines].filter((line) => !current.split(/\r?\n/).includes(line));
  if (next.length) writeFileSync(path, `${current}${current && !current.endsWith("\n") ? "\n" : ""}${next.join("\n")}\n`);
}

function cmdInit(opt) {
  const target = opt.target;
  const config = readJson(join(target, CONFIG_FILE)) || baseConfig(target, opt);
  const dirs = [
    ".iak/manifest",
    config.paths.feedback,
    config.paths.runs,
    config.paths.pages,
    config.paths.features,
    config.paths.componentsUi,
    config.paths.componentsApp,
    config.paths.layouts,
    config.paths.typesGenerated,
    config.generated.routes,
    config.generated.actions,
  ];
  const plan = filePlan(target, initFiles(config), opt.apply);
  if (opt.apply) {
    for (const dir of dirs) ensureDir(join(target, dir));
    writeJson(join(target, CONFIG_FILE), config);
    writeJson(join(target, ".iak/config.json"), config);
    appendGitignore(target);
    writeManifest(target, config);
  }
  return output(opt, {
    schema: "iak.init.v1",
    status: "completed",
    applied: opt.apply,
    config: CONFIG_FILE,
    adapter: config.project.adapter,
    directories: dirs,
    plan,
  });
}

function generatedTypesFor(resource) {
  const singularName = singular(resource);
  const ns = pascal(singularName);
  return `${GENERATED_HEADER}

export namespace App {
  export namespace Data {
    export namespace ${pascal(resource)} {
      export type ${ns}ListItemData = {
        id: number
        name: string
        status: { value: string; label: string }
        createdAt: { value: string; label: string }
      }

      export type ${ns}FiltersData = {
        search: string
        status: string | null
      }

      export type ${ns}FormData = {
        name: string
        status: string
      }

      export type ${ns}IndexPageData = {
        ${resource}: ${ns}ListItemData[]
        filters: ${ns}FiltersData
        copy: { title: string; createLabel: string; emptyTitle: string }
        can: { create: boolean }
        meta: { title: string; description: string | null }
      }

      export type ${ns}ShowPageData = {
        ${singularName}: ${ns}ListItemData
        copy: { title: string; editLabel: string }
        can: { update: boolean; delete: boolean }
        meta: { title: string; description: string | null }
      }

      export type ${ns}CreatePageData = {
        form: ${ns}FormData
        copy: { title: string; submitLabel: string }
        meta: { title: string; description: string | null }
      }

      export type ${ns}EditPageData = {
        ${singularName}: ${ns}ListItemData
        form: ${ns}FormData
        copy: { title: string; submitLabel: string }
        meta: { title: string; description: string | null }
      }
    }
  }
}
`;
}

function resourceFiles(config, resource) {
  const item = singular(resource);
  const Item = pascal(item);
  const Items = pascal(resource);
  const itemVar = camel(item);
  const resourceVar = camel(resource);
  const pages = `${config.paths.pages}/${resource}`;
  const features = `${config.paths.features}/${resource}`;
  return [
    {
      path: `${config.paths.typesGenerated}/${resource}.d.ts`,
      content: generatedTypesFor(resource),
    },
    {
      path: `${features}/${item}.types.ts`,
      content: `import type { App } from '@/types/generated/${resource}'

export type ${Item}ListItem = App.Data.${Items}.${Item}ListItemData
export type ${Item}Filters = App.Data.${Items}.${Item}FiltersData
export type ${Item}FormData = App.Data.${Items}.${Item}FormData
export type ${Item}IndexPageProps = App.Data.${Items}.${Item}IndexPageData
export type ${Item}ShowPageProps = App.Data.${Items}.${Item}ShowPageData
export type ${Item}CreatePageProps = App.Data.${Items}.${Item}CreatePageData
export type ${Item}EditPageProps = App.Data.${Items}.${Item}EditPageData
`,
    },
    {
      path: `${features}/${item}.fixtures.ts`,
      content: `import type { ${Item}CreatePageProps, ${Item}IndexPageProps, ${Item}ListItem } from './${item}.types'

export const ${itemVar}Fixture: ${Item}ListItem = {
  id: 1,
  name: 'Fleet Sedan',
  status: { value: 'active', label: 'Active' },
  createdAt: { value: '2026-05-22T00:00:00Z', label: 'May 22, 2026' },
}

export const ${itemVar}IndexPageFixture: ${Item}IndexPageProps = {
  ${resource}: [${itemVar}Fixture],
  filters: { search: '', status: null },
  copy: { title: '${Items}', createLabel: 'Create ${Item}', emptyTitle: 'No ${resource} yet' },
  can: { create: true },
  meta: { title: '${Items}', description: null },
}

export const ${itemVar}CreatePageFixture: ${Item}CreatePageProps = {
  form: { name: '', status: 'draft' },
  copy: { title: 'Create ${Item}', submitLabel: 'Save ${Item}' },
  meta: { title: 'Create ${Item}', description: null },
}
`,
    },
    {
      path: `${features}/${item}-table.tsx`,
      content: `import type { ${Item}ListItem } from './${item}.types'

export function ${Item}Table({ ${resourceVar} }: { ${resourceVar}: ${Item}ListItem[] }) {
  if (!${resourceVar}.length) return null

  return (
    <table className="w-full border-collapse text-ds-fg">
      <thead>
        <tr className="border-b border-ds-border">
          <th className="py-2 text-left">Name</th>
          <th className="py-2 text-left">Status</th>
          <th className="py-2 text-left">Created</th>
        </tr>
      </thead>
      <tbody>
        {${resourceVar}.map((${itemVar}) => (
          <tr key={${itemVar}.id} className="border-b border-ds-border">
            <td className="py-2">{${itemVar}.name}</td>
            <td className="py-2">{${itemVar}.status.label}</td>
            <td className="py-2">{${itemVar}.createdAt.label}</td>
          </tr>
        ))}
      </tbody>
    </table>
  )
}
`,
    },
    {
      path: `${features}/${item}-table.stories.tsx`,
      content: `import type { Meta, StoryObj } from '@storybook/react'
import { ${Item}Table } from './${item}-table'
import { ${itemVar}Fixture } from './${item}.fixtures'

const meta = {
  title: 'Features/${Items}/${Item}Table',
  component: ${Item}Table,
  args: { ${resourceVar}: [${itemVar}Fixture] },
} satisfies Meta<typeof ${Item}Table>

export default meta
export const Populated: StoryObj<typeof meta> = {}
export const Empty: StoryObj<typeof meta> = { args: { ${resourceVar}: [] } }
`,
    },
    {
      path: `${features}/${item}-filters.tsx`,
      content: `import type { ${Item}Filters } from './${item}.types'

export function ${Item}Filters({ filters }: { filters: ${Item}Filters }) {
  return (
    <div className="flex gap-4 border-b border-ds-border py-4">
      <span className="text-ds-fg">{filters.search || 'All ${resource}'}</span>
      <span className="text-ds-fg">{filters.status || 'Any status'}</span>
    </div>
  )
}
`,
    },
    {
      path: `${features}/${item}-form.tsx`,
      content: `import { Button } from '@/components/ui/button'
import type { ${Item}FormData } from './${item}.types'

export function ${Item}Form({ form, submitLabel }: { form: ${Item}FormData; submitLabel: string }) {
  return (
    <form className="grid gap-4">
      <label className="grid gap-2 text-ds-fg">
        <span>Name</span>
        <input className="rounded border border-ds-border bg-ds-surface p-2" defaultValue={form.name} name="name" />
      </label>
      <Button type="submit">{submitLabel}</Button>
    </form>
  )
}
`,
    },
    {
      path: `${features}/${item}-form.stories.tsx`,
      content: `import type { Meta, StoryObj } from '@storybook/react'
import { ${Item}Form } from './${item}-form'
import { ${itemVar}CreatePageFixture } from './${item}.fixtures'

const meta = {
  title: 'Features/${Items}/${Item}Form',
  component: ${Item}Form,
  args: { form: ${itemVar}CreatePageFixture.form, submitLabel: ${itemVar}CreatePageFixture.copy.submitLabel },
} satisfies Meta<typeof ${Item}Form>

export default meta
export const Default: StoryObj<typeof meta> = {}
`,
    },
    {
      path: `${features}/${item}-empty-state.tsx`,
      content: `export function ${Item}EmptyState({ title }: { title: string }) {
  return (
    <div className="rounded border border-ds-border bg-ds-muted p-4 text-ds-fg">
      {title}
    </div>
  )
}
`,
    },
    {
      path: `${pages}/index.tsx`,
      content: `import type { ReactNode } from 'react'
import { AppLayout } from '@/layouts/app-layout'
import { ${Item}EmptyState } from '@/features/${resource}/${item}-empty-state'
import { ${Item}Filters } from '@/features/${resource}/${item}-filters'
import { ${Item}Table } from '@/features/${resource}/${item}-table'
import type { ${Item}IndexPageProps } from '@/features/${resource}/${item}.types'

export default function ${Items}Index(props: ${Item}IndexPageProps) {
  return (
    <section className="grid gap-4 p-4">
      <header>
        <h1 className="text-ds-fg">{props.copy.title}</h1>
      </header>
      <${Item}Filters filters={props.filters} />
      {props.${resource}.length ? (
        <${Item}Table ${resourceVar}={props.${resource}} />
      ) : (
        <${Item}EmptyState title={props.copy.emptyTitle} />
      )}
    </section>
  )
}

${Items}Index.layout = (page: ReactNode) => <AppLayout>{page}</AppLayout>
`,
    },
    {
      path: `${pages}/show.tsx`,
      content: `import type { ReactNode } from 'react'
import { AppLayout } from '@/layouts/app-layout'
import type { ${Item}ShowPageProps } from '@/features/${resource}/${item}.types'

export default function ${Items}Show(props: ${Item}ShowPageProps) {
  return (
    <section className="grid gap-4 p-4">
      <h1 className="text-ds-fg">{props.${item}.name}</h1>
      <p className="text-ds-fg">{props.${item}.status.label}</p>
    </section>
  )
}

${Items}Show.layout = (page: ReactNode) => <AppLayout>{page}</AppLayout>
`,
    },
    {
      path: `${pages}/create.tsx`,
      content: `import type { ReactNode } from 'react'
import { AppLayout } from '@/layouts/app-layout'
import { ${Item}Form } from '@/features/${resource}/${item}-form'
import type { ${Item}CreatePageProps } from '@/features/${resource}/${item}.types'

export default function ${Items}Create(props: ${Item}CreatePageProps) {
  return (
    <section className="grid gap-4 p-4">
      <h1 className="text-ds-fg">{props.copy.title}</h1>
      <${Item}Form form={props.form} submitLabel={props.copy.submitLabel} />
    </section>
  )
}

${Items}Create.layout = (page: ReactNode) => <AppLayout>{page}</AppLayout>
`,
    },
    {
      path: `${pages}/edit.tsx`,
      content: `import type { ReactNode } from 'react'
import { AppLayout } from '@/layouts/app-layout'
import { ${Item}Form } from '@/features/${resource}/${item}-form'
import type { ${Item}EditPageProps } from '@/features/${resource}/${item}.types'

export default function ${Items}Edit(props: ${Item}EditPageProps) {
  return (
    <section className="grid gap-4 p-4">
      <h1 className="text-ds-fg">{props.copy.title}</h1>
      <${Item}Form form={props.form} submitLabel={props.copy.submitLabel} />
    </section>
  )
}

${Items}Edit.layout = (page: ReactNode) => <AppLayout>{page}</AppLayout>
`,
    },
  ];
}

function cmdNew(opt) {
  const kind = opt._[1];
  if (kind !== "resource") throw new Error("Usage: iak new resource <resource>");
  const resource = opt._[2];
  if (!resource) throw new Error("Usage: iak new resource <resource>");
  const config = loadConfig(opt.target);
  const files = resourceFiles(config, kebab(resource));
  const plan = filePlan(opt.target, files, opt.apply);
  if (opt.apply) {
    writeManifest(opt.target, config);
  }
  return output(opt, {
    schema: "iak.scaffold.v1",
    status: plan.review.length ? "blocked" : "completed",
    applied: opt.apply,
    resource: kebab(resource),
    plan,
  }, plan.review.length ? 1 : 0);
}

function walkFiles(root, callback) {
  let entries;
  try { entries = readdirSync(root); } catch { return; }
  for (const entry of entries) {
    if (SKIP_DIRS.has(entry)) continue;
    const full = join(root, entry);
    const stat = statSync(full);
    if (stat.isDirectory()) walkFiles(full, callback);
    else callback(full);
  }
}

function addViolation(violations, v) {
  violations.push({
    id: `vio_${String(violations.length + 1).padStart(3, "0")}`,
    severity: "error",
    confidence: "high",
    ...v,
  });
}

function roleFor(config, rel) {
  if (rel.startsWith(`${config.paths.pages}/`)) return "page";
  if (rel.startsWith(`${config.paths.features}/`)) return "feature";
  if (rel.startsWith(`${config.paths.componentsUi}/`)) return "primitive";
  if (rel.startsWith(`${config.paths.componentsApp}/`)) return "app-component";
  if (rel.startsWith(`${config.paths.typesGenerated}/`)) return "type";
  if (rel.startsWith(`${config.paths.layouts}/`)) return "layout";
  return "unknown";
}

function scanSource(target, config, violations) {
  walkFiles(target, (file) => {
    if (!SCAN_EXT.has(extname(file))) return;
    const rel = relPath(target, file);
    const text = readFileSync(file, "utf8");
    const isToken = TOKEN_FILE.test(rel);
    text.split(/\r?\n/).forEach((line, index) => {
      for (const m of line.matchAll(ARBITRARY)) {
        addViolation(violations, {
          rule: "iak/design-system/no-arbitrary-values",
          category: "design-system",
          file: rel,
          line: index + 1,
          role: roleFor(config, rel),
          hit: m[0].trim(),
          message: "Arbitrary utility values are forbidden. Add or use a semantic token.",
        });
      }
      if (!isToken) {
        for (const m of line.matchAll(RAW_HEX)) {
          addViolation(violations, {
            rule: "iak/design-system/no-raw-hex",
            category: "design-system",
            file: rel,
            line: index + 1,
            role: roleFor(config, rel),
            hit: m[0],
            message: "Raw hex colors are forbidden outside token files.",
          });
        }
        for (const m of line.matchAll(PRIMITIVE_COLOR)) {
          addViolation(violations, {
            rule: "iak/design-system/no-primitive-color-utility",
            category: "design-system",
            file: rel,
            line: index + 1,
            role: roleFor(config, rel),
            hit: m[0].trim(),
            message: "Primitive color utilities are forbidden. Use ds semantic utilities.",
          });
        }
      }
    });

    if (roleFor(config, rel) === "page" && /\b(?:interface|type)\s+\w*PageProps\b/.test(text)) {
      addViolation(violations, {
        rule: "iak/page/no-backend-prop-types",
        category: "page",
        file: rel,
        line: 1,
        role: "page",
        hit: "PageProps",
        message: "Pages must import backend-derived page props instead of defining them locally.",
      });
    }
  });
}

function scanStructure(target, config, violations) {
  for (const name of FORBIDDEN_TOP_LEVEL) {
    const path = join(target, config.paths.root, name);
    if (existsSync(path)) {
      addViolation(violations, {
        rule: "iak/role/no-global-behavior-buckets",
        category: "role",
        file: `${config.paths.root}/${name}`,
        line: 1,
        role: "unknown",
        hit: name,
        message: `Do not create top-level ${name} folders. Keep behavior resource-local.`,
      });
    }
  }
  const actions = join(target, config.paths.root, "actions");
  if (existsSync(actions)) {
    const entries = readdirSync(actions).filter((entry) => entry !== "generated");
    if (entries.length) {
      addViolation(violations, {
        rule: "iak/role/no-handwritten-global-actions",
        category: "role",
        file: `${config.paths.root}/actions`,
        line: 1,
        role: "unknown",
        hit: entries.join(", "),
        message: "Global actions are reserved for generated Wayfinder output.",
      });
    }
  }

  const features = join(target, config.paths.features);
  if (!existsSync(features)) return;
  for (const resource of readdirSync(features)) {
    const dir = join(features, resource);
    if (!statSync(dir).isDirectory()) continue;
    const item = singular(resource);
    const typesPath = join(dir, `${item}.types.ts`);
    if (existsSync(typesPath) && !readFileSync(typesPath, "utf8").includes("@/types/generated")) {
      addViolation(violations, {
        rule: "iak/types/generated-import-required",
        category: "types",
        file: relPath(target, typesPath),
        line: 1,
        role: "feature",
        resource,
        hit: basename(typesPath),
        message: "Feature type aliases must compose generated backend types.",
      });
    }
    for (const base of [`${item}-table`, `${item}-form`]) {
      const component = join(dir, `${base}.tsx`);
      const story = join(dir, `${base}.stories.tsx`);
      if (existsSync(component) && !existsSync(story)) {
        addViolation(violations, {
          rule: "iak/stories/reusable-feature-story-required",
          category: "stories",
          file: relPath(target, component),
          line: 1,
          role: "feature",
          resource,
          hit: basename(component),
          message: "Stateful/reusable feature UI must have a colocated story.",
        });
      }
    }
  }
}

function auditProject(target, opt = {}) {
  const config = loadConfig(target);
  const violations = [];
  scanSource(target, config, violations);
  scanStructure(target, config, violations);
  const status = violations.length ? "failed" : "passed";
  const id = runId(opt);
  const result = {
    schema: "iak.audit.v1",
    runId: id,
    status,
    summary: status === "passed"
      ? "Audit passed: no IAK convention violations found."
      : `Audit failed: ${violations.length} IAK convention violation(s).`,
    checks: [
      {
        id: "iak/conventions/core",
        category: "manifest",
        status,
        severity: "error",
        violations: violations.length,
      },
    ],
    violations,
    artifacts: {
      full: { kind: "json", path: `.iak/runs/${id}/audit.json` },
    },
    nextActions: violations.map((v) => ({
      type: "fix",
      summary: v.message,
      rule: v.rule,
      file: v.file,
      line: v.line,
    })),
    errors: [],
    meta: {
      adapter: config.project.adapter,
      createdAt: now(),
    },
  };
  writeJson(join(target, ".iak/runs", id, "audit.json"), result);
  writeJson(join(target, ".iak/runs", id, "audit", "audit.json"), result);
  return result;
}

function cmdAudit(opt) {
  const result = auditProject(opt.target, opt);
  return output(opt, result, result.status === "passed" ? 0 : 1);
}

function readFeedbackRecords(target) {
  const root = join(target, ".iak/feedback");
  if (!existsSync(root)) return [];
  const records = [];
  for (const name of readdirSync(root).sort()) {
    const path = join(root, name, "record.json");
    if (existsSync(path)) {
      const record = readJson(path);
      if (record) records.push(record);
    }
  }
  return records;
}

function writeFeedback(target, record) {
  writeJson(join(target, ".iak/feedback", record.id, "record.json"), record);
}

function cmdFeedback(opt) {
  const action = opt._[1];
  if (action === "create") return feedbackCreate(opt);
  if (action === "list") return feedbackList(opt);
  if (action === "show") return feedbackShow(opt);
  if (action === "resolve") return feedbackResolve(opt);
  throw new Error("Usage: iak feedback create|list|show|resolve");
}

function feedbackCreate(opt) {
  if (!opt.message) throw new Error("Usage: iak feedback create --message <message>");
  const id = feedbackId(opt);
  const record = {
    schema: "iak.feedback.v1",
    id,
    status: "pending",
    surface: opt.surface || "app",
    source: opt.source || "human",
    producer: opt.producer || "iak.cli",
    target: {
      url: null,
      route: opt.route || null,
      storyId: null,
      selector: null,
      coordinates: null,
    },
    viewport: null,
    message: opt.message,
    tags: [],
    attachments: {
      screenshot: null,
      dom: null,
      console: null,
      network: null,
      trace: null,
    },
    context: {
      adapter: loadConfig(opt.target).project.adapter,
      componentCandidates: [],
      testRunId: null,
    },
    resolution: null,
    createdAt: now(),
    updatedAt: now(),
  };
  writeFeedback(opt.target, record);
  return output(opt, record);
}

function feedbackList(opt) {
  const status = opt.status || "pending";
  const items = readFeedbackRecords(opt.target)
    .filter((record) => !status || record.status === status)
    .map((record) => ({
      id: record.id,
      status: record.status,
      surface: record.surface,
      source: record.source,
      route: record.target.route,
      message: record.message,
      updatedAt: record.updatedAt,
    }));
  return output(opt, { schema: "iak.feedback.list.v1", status: "completed", items });
}

function feedbackShow(opt) {
  const id = opt._[2];
  if (!id) throw new Error("Usage: iak feedback show <id>");
  const record = readJson(join(opt.target, ".iak/feedback", id, "record.json"));
  if (!record) return output(opt, { schema: "iak.error.v1", status: "blocked", errors: [{ code: "feedback.not_found", message: `Feedback ${id} not found.` }] }, 2);
  return output(opt, record);
}

function feedbackResolve(opt) {
  const id = opt._[2];
  if (!id || !opt.summary || !opt.evidence) {
    throw new Error("Usage: iak feedback resolve <id> --summary <summary> --evidence <path>");
  }
  const record = readJson(join(opt.target, ".iak/feedback", id, "record.json"));
  if (!record) return output(opt, { schema: "iak.error.v1", status: "blocked", errors: [{ code: "feedback.not_found", message: `Feedback ${id} not found.` }] }, 2);
  const evidenceAbs = join(opt.target, opt.evidence);
  if (!existsSync(evidenceAbs)) {
    return output(opt, {
      schema: "iak.error.v1",
      status: "blocked",
      errors: [{ code: "feedback.evidence_missing", message: `Evidence file not found: ${opt.evidence}` }],
    }, 1);
  }
  record.status = "resolved";
  record.updatedAt = now();
  record.resolution = {
    schema: "iak.feedback.resolution.v1",
    summary: opt.summary,
    changedFiles: [],
    commandsRun: [],
    artifacts: { evidence: opt.evidence },
    resolvedAt: now(),
    resolver: { kind: "agent", id: "iak.cli" },
  };
  writeFeedback(opt.target, record);
  return output(opt, record);
}

function writePlaceholderPng(path) {
  ensureDir(dirname(path));
  const png = Buffer.from(
    "iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+/p9sAAAAASUVORK5CYII=",
    "base64",
  );
  writeFileSync(path, png);
}

function cmdVerify(opt) {
  const id = runId(opt);
  const config = loadConfig(opt.target);
  const audit = auditProject(opt.target, { ...opt, runId: id });
  const unresolved = readFeedbackRecords(opt.target).filter((record) => ["pending", "in_progress"].includes(record.status));
  const screenshotPath = `.iak/runs/${id}/screenshots/vehicles-index.desktop.png`;
  const consolePath = `.iak/runs/${id}/console/vehicles-index.desktop.json`;
  writePlaceholderPng(join(opt.target, screenshotPath));
  writeJson(join(opt.target, consolePath), []);
  const passed = audit.status === "passed" && unresolved.length === 0;
  const result = {
    schema: "iak.verify.v1",
    runId: id,
    status: passed ? "passed" : "failed",
    summary: passed
      ? "Verification passed with audit, feedback, and screenshot evidence."
      : "Verification failed. See audit violations or unresolved feedback.",
    audit: {
      status: audit.status,
      artifact: `.iak/runs/${id}/audit.json`,
    },
    feedback: {
      unresolvedCount: unresolved.length,
      records: unresolved.map((record) => ({ id: record.id, route: record.target.route, status: record.status })),
    },
    browser: {
      screenshots: [
        {
          kind: "screenshot",
          route: "vehicles.index",
          viewport: "desktop",
          path: screenshotPath,
          mime: "image/png",
        },
      ],
      console: [{ route: "vehicles.index", path: consolePath }],
    },
    artifacts: {
      full: { kind: "json", path: `.iak/runs/${id}/verify.json` },
    },
    nextActions: [
      ...audit.nextActions,
      ...unresolved.map((record) => ({
        type: "resolve_feedback",
        summary: record.message,
        feedbackId: record.id,
      })),
    ],
    errors: [],
    meta: {
      adapter: config.project.adapter,
      createdAt: now(),
    },
  };
  writeJson(join(opt.target, ".iak/runs", id, "verify.json"), result);
  return output(opt, result, passed ? 0 : 1);
}

function output(opt, value, exitCode = 0) {
  if (opt.json) console.log(JSON.stringify(value, null, 2));
  else {
    const status = value.status ? ` ${value.status}` : "";
    console.log(`  iak${status}`);
    if (value.summary) console.log(`  ${value.summary}`);
  }
  process.exit(exitCode);
}

export function main(args = process.argv.slice(2)) {
  const opt = parse(args);
  const cmd = opt._[0];
  try {
    if (cmd === "init") return cmdInit(opt);
    if (cmd === "new") return cmdNew(opt);
    if (cmd === "audit") return cmdAudit(opt);
    if (cmd === "feedback") return cmdFeedback(opt);
    if (cmd === "verify") return cmdVerify(opt);
    console.log(`Inertia Agent Kit

  iak init [--apply] [--json]
  iak new resource <resource> [--apply] [--json]
  iak audit [--json]
  iak feedback create|list|show|resolve [--json]
  iak verify [--json]
`);
  } catch (error) {
    const payload = {
      schema: "iak.error.v1",
      status: "blocked",
      errors: [{ code: "command.failed", message: error.message }],
    };
    if (opt.json) console.error(JSON.stringify(payload, null, 2));
    else console.error(`  Error: ${error.message}`);
    process.exit(2);
  }
}

if (import.meta.url === `file://${process.argv[1]}`) {
  main();
}
